version: "3.8"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
  # app: 
  #   container_name: bankan
  #   build: 
  #     context: .
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=123456
  #   depends_on:
  #     - db

